version: '3.8'

services:
  laravel:
    build:
      context: .
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php artisan serve --host=0.0.0.0 --port=9000
    ports:
      - "9000:9000"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 💥 Ini yang penting
    restart: unless-stopped

volumes:
  jenkins-data:
